version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      
      - DATABASE_URL=postgres://usuario:senha@db:5432/escola_infantil
    command: npm start
    working_dir: /usr/src/app
    volumes:
      - node_modules:/usr/src/app/APP/node_modules

  db:
    
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: escola_infantil
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./ProjetoADS:/docker-entrypoint-initdb.d

volumes:
  db_data:
  node_modules: